development:
  adapter: postgresql
  encoding: unicode
  database: translator_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: translator_test
  pool: 5
  username: postgres
  password: password
  host: localhost